---

- hosts: synapse
  remote_user: vagrant
  sudo: yes
  sudo_user: root
  vars_files:
      - synapse_vars.yml

  tasks:
    - name: Install packages needed by synapse
      action: apt pkg={{item}} state=installed
      with_items:
       - build-essential
       - python2.7-dev
       - libffi-dev
       - python-pip
       - python-setuptools
       - sqlite3
       - libssl-dev
       - python-virtualenv
       - libjpeg-dev

    - name: Create synapse user
      user: name={{ username }} shell=/bin/bash comment="{{ username }}" groups=admin,sudo

    - name: Create virtualenv
      command: virtualenv -p python2.7 ~/.synapse
      args:
        chdir: /home/{{ username }}

    - name: PIP upgrade setup tools
      pip: name=setuptools virtualenv=/home/{{ username }}/.synapse extra_args='--upgrade'

    - name: PIP install into virtualenv
      pip: name={{ git_repo }} virtualenv=/home/{{ username }}/.synapse

    - name: Generate homeserver.yaml config file
      shell: ". bin/activate && python -m synapse.app.homeserver --server-name {{ hostname }} --config-path homeserver.yaml --generate-config --report-stats=yes"
      args:
        chdir: /home/{{ username }}/.synapse/
        creates: /home/{{ username }}/.synapse/homeserver.yaml

    - name: Configure if registrations are enabled by default or not
      lineinfile: dest=/home/{{ username }}/.synapse/homeserver.yaml
      args:
        regexp: "^enable_registration:"
        line: "enable_registration: {{ enable_registration }}"

    - name: Configure if captchas are enabled by default or not
      lineinfile: dest=/home/{{ username }}/.synapse/homeserver.yaml
      args:
        regexp: "^enable_registration_captcha:"
        line: "enable_registration_captcha: {{ enable_registration_captcha }}"

    - name: Configure private-key recaptch key
      lineinfile: dest=/home/{{ username }}/.synapse/homeserver.yaml
      args:
        regexp: "^recaptcha_private_key:"
        line: "recaptcha_private_key: {{ recaptcha_private_key }}"

    - name: Configure public-key rceaptch key
      lineinfile: dest=/home/{{ username }}/.synapse/homeserver.yaml
      args:
        regexp: "^recaptcha_public_key:"
        line: "recaptcha_public_key: {{ recaptcha_public_key }}"

    - name: Set permissions
      file:
        path='/home/{{ username }}/.synapse'
        state=directory
        owner={{ username }}
        group={{ username }}
        recurse=yes

    - name: Install upstart script
      template:
        src=init/synapse.conf
        dest=/etc/init/synapse.conf

    - name: Start synapse server
      service: name=synapse state=started
